### ISSUE TITLE
Can't unequip Book of Scholars in new version.

### ISSUE THREAD

**Issue by james-tindal** [kpwn243/melvor-quick-equip-manager#4]
Melvor released version 1.2.

The previous bug doesn't seem to come up any more. Now there's a different one.

When you try to unequip Book of Scholars, it doesn't work. It logs an error to the console. "Error: Unknown slot translation Shield"

**Comment by Drake-W** [comment]
Book of the Ancients has the issue also. Any item you try to equip in their place gets deleted and these two get duplicated into the bank every time you try to unequip.

**Comment by kpwn243** [comment]
This has been fixed
